pr10/urls.py
from django.contrib import admin
from django.urls import path,include
from pr10 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample/',views.sample,name="sample"),
    path('register/',views.register,name="register"),
    path('stu/',include('studentform.urls')),
]

studentform/urls.py
from django.urls import path
from studentform import views
urlpatterns=[
    path('form/',views.pyreg,name='form')
]

studentform/models.py
from django.db import models

# Create your models here.

class form(models.Model):
    full_name=models.CharField(max_length=50)
    gender=models.CharField(max_length=6)
    dob=models.DateField()
    phone=models.BigIntegerField()
    email=models.EmailField()
    ten_th=models.CharField(max_length=20)
    puc=models.CharField(max_length=20)
    diploma=models.CharField(max_length=15)
    aggregate_12=models.FloatField()
    aggregate_diploma=models.FloatField()
    yop_12=models.IntegerField()
    yop_diploma=models.IntegerField()
    diploma_college=models.CharField(max_length=50)
    diploma_branch=models.CharField(max_length=50)
    diploma_branch_other=models.CharField(max_length=50)
    degree=models.CharField(max_length=10)
    degree_branch=models.CharField(max_length=20)
    degree_branch_other=models.CharField(max_length=50)
    agreegate_degree=models.FloatField()
    degree_yop=models.DateField()
    uni_name=models.CharField(max_length=50)
    usn=models.CharField(max_length=30)
    clg_name=models.CharField(max_length=50)
    place_clg=models.CharField(max_length=50)
    backlog=models.CharField(max_length=5)
    current_backlog=models.CharField(max_length=5)
    gap_in_degree=models.CharField(max_length=5)
    master=models.CharField(max_length=10)
    master_qualification=models.CharField(max_length=20)
    master_degree=models.CharField(max_length=20)
    other_master_degree=models.CharField(max_length=20)
    aggrigate_master=models.IntegerField()
    master_yop=models.DateField()
    master_uni_name=models.CharField(max_length=50)
    master_usn=models.CharField(max_length=50)
    master_clg_name=models.CharField(max_length=50)
    Master_clg_place=models.CharField(max_length=30)
    master_fail_clear=models.CharField(max_length=10)
    master_existing_backlog=models.CharField(max_length=5)
    year_gap_master=models.CharField(max_length=5)
    certificate=models.CharField(max_length=30)
    ready_to_relocate=models.CharField(max_length=5)
    Location=models.CharField(max_length=150)
    you_have_passport=models.CharField(max_length=10)
    you_have_pancard=models.CharField(max_length=10)
    you_have_adharcard=models.CharField(max_length=10)
    aadhar_no=models.BigIntegerField()
    father_name=models.CharField(max_length=30)
    house_no=models.CharField(max_length=30)
    street_no=models.CharField(max_length=30)
    area_name=models.CharField(max_length=30)
    pincode=models.IntegerField()
    city=models.CharField(max_length=30)
    state=models.CharField(max_length=30)
    
    
    
    

pr10/views.py
from django.shortcuts import render

def sample(request):
    print(request)
    if request.method=='GET':
        print(type(request.GET))
        user=request.GET.get('username')
        pass1=request.GET.get('password')
        email=request.GET.get('email')
        phone=request.GET.get('phone')
        print(user,pass1,email,phone)
    return render(request,'sample.html')

def register(request):
    print(request)
    if request.method=='POST':
        print(type(request.POST))
        print(request.POST)
        user=request.POST['username'] #  user=request.POST.get('username')
        pass1=request.POST['password']
        email=request.POST['email']
        phone=request.POST['phone']
        print(user,pass1,email,phone)
    return render(request,'register.html')

studentform/views.py
from django.shortcuts import render
from studentform.models import form
from django.http import HttpResponse
# Create your views here.
def pyreg(request):
    if request.method=="POST":
        print(request.POST)
        if request.POST['phone']==request.POST['phone_repeat'] and request.POST['email']==request.POST['email_repeat'] :
            form.objects.create(full_name=request.POST['full_name'],
                        gender=request.POST['gender'],
                        dob=request.POST['dob'], 
                        phone=request.POST['phone'], 
                        email=request.POST['email'],
                        ten_th=request.POST['ten_th'], 
                        puc=request.POST['puc'],
                        diploma=request.POST['diploma'], 
                        aggregate_12=request.POST['aggregate_12'], 
                        aggregate_diploma=request.POST['aggregate_diploma'], 
                        yop_12=request.POST['yop_12'], 
                        yop_diploma=request.POST['yop_diploma'], 
                        diploma_college=request.POST['diploma_college'], 
                        diploma_branch=request.POST['diploma_branch'], 
                        diploma_branch_other=request.POST['diploma_branch_other'], 
                        degree=request.POST['degree'], 
                        degree_branch=request.POST['degree_branch'], 
                        degree_branch_other=request.POST['degree_branch_other'], 
                        agreegate_degree=request.POST['agreegate_degree'], 
                        degree_yop=request.POST['degree_yop'], 
                        uni_name=request.POST['uni_name'], 
                        usn=request.POST['usn'], 
                        clg_name=request.POST['clg_name'], 
                        place_clg=request.POST['place_clg'], 
                        backlog=request.POST['backlog'], 
                        current_backlog=request.POST['current_backlog'], 
                        gap_in_degree=request.POST['gap_in_degree'], 
                        master=request.POST['master'], 
                        master_qualification=request.POST['master_qualification'], 
                        master_degree=request.POST['master_degree'], 
                        other_master_degree=request.POST['other_master_degree'], 
                        aggrigate_master=request.POST['aggrigate_master'], 
                        master_yop=request.POST['master_yop'], 
                        master_uni_name=request.POST['master_uni_name'], 
                        master_usn=request.POST['master_usn'], 
                        master_clg_name=request.POST['master_clg_name'], 
                        Master_clg_place=request.POST['Master_clg_place'], 
                        master_fail_clear=request.POST['master_fail_clear'], 
                        master_existing_backlog=request.POST['master_existing_backlog'], 
                        year_gap_master=request.POST['year_gap_master'], 
                        certificate=request.POST['certificate'], 
                        ready_to_relocate=request.POST['ready_to_relocate'], 
                        Location=request.POST.getlist('Location'), 
                        you_have_passport=request.POST['you_have_passport'],
                        you_have_pancard=request.POST['you_have_pancard'], 
                        you_have_adharcard=request.POST['you_have_adharcard'], 
                        aadhar_no=request.POST['aadhar_no'], 
                        father_name=request.POST['father_name'], 
                        house_no=request.POST['house_no'], 
                        street_no=request.POST['street_no'], 
                        area_name=request.POST['area_name'], 
                        pincode=request.POST['pincode'], 
                        city=request.POST['city'], 
                        state=request.POST['state'])
            return HttpResponse("your responce submit successfull")
    return render(request,"form.html")

templates/back.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>py form</title>
</head>
<body>
   
    <form action="">
        <div style="border: 2px solid green;"> 
            <header style="text-align: center; margin: 19.92px 0px;">
                <h2 style="text-decoration: underline; display: inline; ">Master deree of post graduation:</h2>
                <label for=""> regular</label><input type="checkbox" name="master_degree" value="regular">
                <label for="">Correspondence</label><input type="checkbox" name="master_degree" value="correspondence">
            </header>

            <div id="one" style="border: 2px solid black; margin: 20px; padding: 10px;">
        
                <div class="degree" style=" margin-left: 10px;">
                    <label for="">M tech</lable><input type="checkbox" name="master_qualification" value="m.tech">
                    <lable for="">MCA</lable><input type="checkbox" name="master_qualification" value="MCA">
                    <lable for="">M.Sc</lable><input type="checkbox" name="master_qualification" value="M.Sc">
                    <lable for="">MBA</lable><input type="checkbox" name="master_qualification" value="MBA">
                    <lable for="">Ms</lable><input type="checkbox" name="master_qualification" value="Ms">
                    
                </div>
                <div class="degree" style="margin-bottom: 10px; margin-left: 10px;">
                    <span>stream:</span>
                    <lable  for="">C Sc</lable><input type="checkbox" name="master_degree" value="CSc">
                    <lable  for="">IT</lable><input type="checkbox" name="master_degree" value="IT">
                    <lable for="">EEE</lable><input type="checkbox" name="master_degree" value="EEE">
                    <lable for="">IS</lable><input type="checkbox" name="master_degree" value="IS">
                    <lable for="">EC</lable><input type="checkbox" name="master_degree" value="EC">
                    <lable for="">Mech</lable><input type="checkbox" name="master_degree" value="Mech">
                    <lable for="">Civil</lable><input type="checkbox" name="master_degree" value="Civil">
                    <lable for="">Other</lable><input type="checkbox" name="master_degree" value="other_master_degree">
                    
                </div>
                <table >
                    <tr>         
                        <td><label for="">Other</label> </td><td>  <input type="text" name="other_master_degree"></td>
                        <td><label for="">percentage(1 to 8 sesm)</label></td><td> <input type="number" name="aggrigate_masater"></td>
                        <td ><label for="">year of passing</label><input type="date" name="master_yop"></td>
                    </tr>
                    <tr>
                        <td><label for="">University</label></td><td> <input type="text" name="master_uni_name"></td>
                        <td><label for="">unniversity roll(usn) no.</label></td><td> <input type="text" name="master_usn"></td>
                        <td rowspan="2"></td>
                    </tr>
                    <tr>
                        <td><label for="">Collage Name</label></td><td> <input type="text" name="master_clg_name"></td>
                        <td><label for="">Place</label></td><td> <input type="text" name="Master_clg_place"></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <span>Did you fail and then clear the subject in degree:</span>
                            <label for="">yes</label><input type="checkbox" name="master_fail_clear" value="yes">
                            <label for="">No</label><input type="checkbox" name="master_fail_clear" value="no">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <span>have any existing backlog:</span>
                            <label for="">yes</label><input type="checkbox" name="master_existing_backlog" value="yes">
                            <label for="">No</label><input type="checkbox" name="master_existing_backlog" value="no">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <span>got year gap in degree:</span>
                            <label for="">yes</label><input type="checkbox" name="year_gap_master" value="yes">
                            <label for="">No</label><input type="checkbox" name="year_gap_master" value="no">
                        </td>
                    </tr>
                </table>
            </div>
            <div id="two" style="border: 2px solid black; margin: 20px; padding: 10px;"> 
                <table>
                    <tr>
                        <td> <label for="">Certifications:</label></td>
                        <td><input type="text" width="500px" placeholder="Only international certified s/w cedrtifications" name="certificate" >
                        </td>
                    </tr>
                    <tr>
                        <td>  <span>Ready to relocte to work:</span></td>
                        <td><label for="">yes</label><input type="checkbox" name="ready_to_relocate" value="yes">
                            <label for="">No</label><input type="checkbox"  name="ready_to_relocate" value="no">
                        </td>
                    </tr>
                    <tr>
                        <td><span> If yes, preferred Location:</span></td>
                        <td> <label for="">Bengaluru</label><input type="checkbox">
                            <label for="">Chennai</label><input type="checkbox">
                            <label for="">Hyderabad</label><input type="checkbox">
                            <label for="">Kerala</label><input type="checkbox">
                            <label for="">Pune</label><input type="checkbox">
                            <label for="">Mumbai</label><input type="checkbox">
                            <label for="">Delhi</label><input type="checkbox">
                            <label for="">Gandhinagar</label><input type="checkbox">
                            <label for="">Other</label><input type="text">
                        </td>
                    </tr>
                    <tr>
                        <td><span>Do you have passport:</span></td>
                        <td><label for="">yes</label><input type="checkbox" name="you_have_passport" value="yes">
                            <label for="">No</label><input type="checkbox" name="you_have_passport" value="no"> 
                        </td>
                    </tr>
                    <tr>
                        <td><span>Do you have pan card:</span></td>
                        <td><label for="">yes</label><input type="checkbox" name="you_have_pancard" value="yes">
                            <label for="">No</label><input type="checkbox" name="you_have_pancard" value="no">
                        </td>
                    </tr>
                    <tr>
                        <td><span>Do you have adhar card:</span></td>
                        <td><label for="">yes</label><input type="checkbox" name="you_have_adharcard" value="yes">
                            <label for="">No</label><input type="checkbox" name="you_have_adharcard" value="no">
                            <label for="">adhar no.</label><input type="text" name="aadhar no.">
                        </td>
                    </tr>
                </table>
            </div>

            <header style=" margin: 19.92px 20px;">
                <h2 style="text-decoration: underline; display: inline; ">Address :</h2>
            </header>
            <div id="three" style="border: 2px solid black; margin: 20px; padding: 10px;">
                <table>
                    <tr>
                        <td colspan="2">
                            <label for="">Father/Husband's name :</label>
                        </td>
                        <td colspan="2">
                            <input type="text" name="father/husband_name" id="">
                        </td>
                     
                    </tr>
                    <tr>
                        <td><label for="">House no.</label></td>
                        <td><input type="text" name="house_no" id=""></td>
                        <td><label for="">Street no.</label></td>
                        <td><input type="text" name="street_no" id=""></td>
                    </tr>
                    <tr>
                        <td><label for="">Area name</label></td>
                        <td><input type="text" name="area_name" id=""></td>
                        <td><label for="">Pin code</label></td>
                        <td><input type="text" name="pincode" id=""></td>
                    </tr>
                    <tr>
                        <td><label for="">City</label></td>
                        <td><input type="text" name="city" id=""></td>
                        <td><label for="">State</label></td>
                        <td><input type="text" name="state" id=""></td>
                    </tr>
                </table>
            </div>
            <div style=" text-align: center;">
                <button  style="margin: 20px;" type="submit">submit</button>
            </div>
        </div>
    </form>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for='id_username'>username</label>
        <input type="text" name='username' id="id_username" required><br>
        
        <label for='id_password'>password</label>
        <input type="password" name='password' id="id_password" required><br>

        <label for='id_email'>email</label>
        <input type="email" name='email' id="id_email" required><br>
        
        <label for='id_phone'>phone</label>
        <input type="number" name='phone' id="id_phone" required><br>
        <button type="submit">Register</button>
        </form>
</body>
</html>

templates/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="get">
        <label for='id_username'>username</label>
        <input type="text" name='username' id="id_username" required><br>
        
        <label for='id_password'>password</label>
        <input type="password" name='password' id="id_password" required><br>

        <label for='id_email'>email</label>
        <input type="email" name='email' id="id_email" required><br>
        
        <label for='id_phone'>phone</label>
        <input type="number" name='phone' id="id_phone" required><br>
        <button type="submit">Register</button>
        </form>
</body>
</html>